// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/blocknative/dreamboat/pkg/validators (interfaces: RegistrationStore)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	structs "github.com/blocknative/dreamboat/pkg/structs"
	types "github.com/flashbots/go-boost-utils/types"
	gomock "github.com/golang/mock/gomock"
)

// MockRegistrationStore is a mock of RegistrationStore interface.
type MockRegistrationStore struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationStoreMockRecorder
}

// MockRegistrationStoreMockRecorder is the mock recorder for MockRegistrationStore.
type MockRegistrationStoreMockRecorder struct {
	mock *MockRegistrationStore
}

// NewMockRegistrationStore creates a new mock instance.
func NewMockRegistrationStore(ctrl *gomock.Controller) *MockRegistrationStore {
	mock := &MockRegistrationStore{ctrl: ctrl}
	mock.recorder = &MockRegistrationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationStore) EXPECT() *MockRegistrationStoreMockRecorder {
	return m.recorder
}

// GetRegistration mocks base method.
func (m *MockRegistrationStore) GetRegistration(arg0 context.Context, arg1 structs.PubKey) (types.SignedValidatorRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistration", arg0, arg1)
	ret0, _ := ret[0].(types.SignedValidatorRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistration indicates an expected call of GetRegistration.
func (mr *MockRegistrationStoreMockRecorder) GetRegistration(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistration", reflect.TypeOf((*MockRegistrationStore)(nil).GetRegistration), arg0, arg1)
}

// PutRegistration mocks base method.
func (m *MockRegistrationStore) PutRegistration(arg0 context.Context, arg1 structs.PubKey, arg2 types.SignedValidatorRegistration, arg3 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutRegistration", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutRegistration indicates an expected call of PutRegistration.
func (mr *MockRegistrationStoreMockRecorder) PutRegistration(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRegistration", reflect.TypeOf((*MockRegistrationStore)(nil).PutRegistration), arg0, arg1, arg2, arg3)
}
